cache: npm
language: node_js
node_js:
  - "node"
env:
  global:
    CC_TEST_REPORTER_ID=e83e66204faea1447e942a520b422232561b064c613293143c09439cd2c30b22
before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - npm install                         # Install npm dependencies
script:
  - npm test                            # Frontend linting & specs
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
